# run with docker-compose up -d

version: "3.9"  
services:
  web:
    image: cientopolis/gapafarm:latest
    restart: unless-stopped
    read_only: true
    environment: 
      DB_HOST: your-mongodb-server-ip
      DB: gapafarm
      ADMIN_EMAIL: user@domain.com
      DEBUG: true  
      DEMO: true 
    ports:
        - "8080:8080"

