Class {
	#name : #SummaryFrecuencyWeekly,
	#superclass : #Object,
	#instVars : [
		'day',
		'hour'
	],
	#category : #'GapAFarm-telegram'
}

{ #category : #accessing }
SummaryFrecuencyWeekly >> day [

	^ day
]

{ #category : #accessing }
SummaryFrecuencyWeekly >> day: anObject [

	day := anObject
]

{ #category : #accessing }
SummaryFrecuencyWeekly >> hour [

	^ hour
]

{ #category : #accessing }
SummaryFrecuencyWeekly >> hour: anObject [

	hour := anObject
]
