Class {
	#name : #SummaryMessageFrecuencyWeekly,
	#superclass : #Object,
	#instVars : [
		'day',
		'hour'
	],
	#category : #'GapAFarm-telegram'
}

{ #category : #accessing }
SummaryMessageFrecuencyWeekly >> day [

	^ day
]

{ #category : #accessing }
SummaryMessageFrecuencyWeekly >> day: anObject [

	day := anObject
]

{ #category : #accessing }
SummaryMessageFrecuencyWeekly >> hour [

	^ hour
]

{ #category : #accessing }
SummaryMessageFrecuencyWeekly >> hour: anObject [

	hour := anObject
]
